/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in with email or username
         * @description Returns an access token (for the `Authorization: Bearer` header) and a longer-lived refresh token. The identifier may be an email address or a username.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description Only refresh tokens are accepted here; access tokens are rejected.
         */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out (revokes all of the user's tokens)
         * @description Invalidates every access and refresh token previously issued to the current user, on all devices.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user profile */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clinic statistics for today
         * @description Patients seen, therapists on duty, revenue collected, open slots, per-therapist capacity and recently added patients, computed live from the database. `date` (clinic-local) defaults to today.
         */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and search patients */
        get: operations["list_patients_api_v1_patients_get"];
        put?: never;
        /** Create a patient */
        post: operations["create_patient_api_v1_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Patient profile
         * @description Patient details plus summary statistics (sessions, next appointment, amounts paid and outstanding).
         */
        get: operations["get_patient_api_v1_patients__patient_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a patient without history
         * @description Only patients with no appointments and no invoices can be deleted; otherwise 409 is returned (set status to COMPLETED or ON_HOLD instead).
         */
        delete: operations["delete_patient_api_v1_patients__patient_id__delete"];
        options?: never;
        head?: never;
        /** Update a patient */
        patch: operations["update_patient_api_v1_patients__patient_id__patch"];
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session history
         * @description The patient's appointments, newest first.
         */
        get: operations["list_patient_appointments_api_v1_patients__patient_id__appointments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patients/{patient_id}/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Billing history
         * @description The patient's invoices, newest first.
         */
        get: operations["list_patient_invoices_api_v1_patients__patient_id__invoices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/therapists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List therapists
         * @description Roster ordered by name, with weekly hours and patients seen today.
         */
        get: operations["list_therapists_api_v1_therapists_get"];
        put?: never;
        /** Create a therapist (admin) */
        post: operations["create_therapist_api_v1_therapists_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/therapists/{therapist_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a therapist */
        get: operations["get_therapist_api_v1_therapists__therapist_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a therapist without appointment history (admin)
         * @description Therapists with any appointments cannot be deleted (409); deactivate them instead. Assigned patients become unassigned.
         */
        delete: operations["delete_therapist_api_v1_therapists__therapist_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update a therapist and their weekly schedule (admin)
         * @description Partial update. Rejected with 409 if the new schedule (or deactivation) would leave upcoming booked appointments outside the therapist's availability.
         */
        patch: operations["update_therapist_api_v1_therapists__therapist_id__patch"];
        trace?: never;
    };
    "/api/v1/therapists/{therapist_id}/schedule-overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List date-specific schedule overrides */
        get: operations["list_overrides_api_v1_therapists__therapist_id__schedule_overrides_get"];
        put?: never;
        /**
         * Create a day-off or custom-hours override (admin)
         * @description One override per therapist and date. Overrides take precedence over the weekly schedule. Rejected with 409 if it would strand upcoming booked appointments.
         */
        post: operations["create_override_api_v1_therapists__therapist_id__schedule_overrides_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/therapists/{therapist_id}/schedule-overrides/{override_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a schedule override (admin) */
        delete: operations["delete_override_api_v1_therapists__therapist_id__schedule_overrides__override_id__delete"];
        options?: never;
        head?: never;
        /** Update a schedule override (admin) */
        patch: operations["update_override_api_v1_therapists__therapist_id__schedule_overrides__override_id__patch"];
        trace?: never;
    };
    "/api/v1/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List appointments */
        get: operations["list_appointments_api_v1_appointments_get"];
        put?: never;
        /**
         * Book an appointment
         * @description Validates the therapist's resolved availability for the date (overrides first, then the weekly schedule), slot alignment and conflicts. `end_time` is derived from the therapist's slot duration. Returns 409 APPOINTMENT_CONFLICT when the slot is taken (also under concurrent requests) and 400 when the slot is not bookable.
         */
        post: operations["create_appointment_api_v1_appointments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/appointments/{appointment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an appointment */
        get: operations["get_appointment_api_v1_appointments__appointment_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel an appointment
         * @description Appointments are clinical history, so DELETE cancels (freeing the slot) instead of erasing the record. Idempotent; completed appointments cannot be cancelled.
         */
        delete: operations["cancel_appointment_api_v1_appointments__appointment_id__delete"];
        options?: never;
        head?: never;
        /**
         * Reschedule or update an appointment
         * @description Changing therapist, date or start time re-runs every booking rule. Status transitions: BOOKED -> COMPLETED | CANCELLED.
         */
        patch: operations["update_appointment_api_v1_appointments__appointment_id__patch"];
        trace?: never;
    };
    "/api/v1/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Slot grid for a date
         * @description For each active therapist (or the given one), every slot of the day with status OPEN, BOOKED (with patient) or THERAPIST_OFF. Slots are generated from the weekly schedule and date overrides; they are not stored.
         */
        get: operations["get_schedule_api_v1_schedule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List invoices */
        get: operations["list_invoices_api_v1_invoices_get"];
        put?: never;
        /**
         * Create an invoice (admin)
         * @description `total` is computed server-side as subtotal - discount. The invoice number is generated (INV-YYYY-NNNNNN).
         */
        post: operations["create_invoice_api_v1_invoices_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/invoices/{invoice_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an invoice */
        get: operations["get_invoice_api_v1_invoices__invoice_id__get"];
        put?: never;
        post?: never;
        /**
         * Void an invoice (admin)
         * @description Invoices are never physically deleted: DELETE sets status VOID, keeping billing history intact. Voided invoices are excluded from revenue. Idempotent.
         */
        delete: operations["void_invoice_api_v1_invoices__invoice_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update an invoice (admin)
         * @description E.g. mark a DUE invoice as PAID. VOID invoices cannot be modified.
         */
        patch: operations["update_invoice_api_v1_invoices__invoice_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (checks database connectivity) */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppointmentCreate */
        AppointmentCreate: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Therapist Id
             * Format: uuid
             */
            therapist_id: string;
            /**
             * Appointment Date
             * Format: date
             * @description Clinic-local date.
             */
            appointment_date: string;
            /**
             * Start Time
             * Format: time
             * @description Must be a slot start in the therapist's schedule. The end time is derived from the therapist's slot duration.
             * @example 09:00
             */
            start_time: string;
            payment_method: components["schemas"]["PaymentMethod"];
            /** @default TREATMENT */
            session_type: components["schemas"]["SessionType"];
            /** Notes */
            notes?: string | null;
        };
        /** AppointmentRead */
        AppointmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Therapist Id
             * Format: uuid
             */
            therapist_id: string;
            /**
             * Appointment Date
             * Format: date
             */
            appointment_date: string;
            /**
             * Start Time
             * @example 09:00
             */
            start_time: string;
            /**
             * End Time
             * @example 09:00
             */
            end_time: string;
            status: components["schemas"]["AppointmentStatus"];
            session_type: components["schemas"]["SessionType"];
            payment_method: components["schemas"]["PaymentMethod"];
            /** Notes */
            notes: string | null;
            patient: components["schemas"]["PatientSummary"];
            therapist: components["schemas"]["TherapistSummary"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * AppointmentStatus
         * @enum {string}
         */
        AppointmentStatus: "BOOKED" | "COMPLETED" | "CANCELLED";
        /**
         * AppointmentUpdate
         * @description Reschedule (therapist/date/start_time), change status or edit details.
         *
         *     Allowed status transitions: BOOKED -> COMPLETED | CANCELLED. COMPLETED and CANCELLED are
         *     final; book a new appointment instead of reviving a cancelled one.
         */
        AppointmentUpdate: {
            /** Therapist Id */
            therapist_id?: string | null;
            /** Appointment Date */
            appointment_date?: string | null;
            /** Start Time */
            start_time?: string | null;
            status?: components["schemas"]["AppointmentStatus"] | null;
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            session_type?: components["schemas"]["SessionType"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * AvailabilitySource
         * @description Why a therapist is (un)available on a given date.
         * @enum {string}
         */
        AvailabilitySource: "REGULAR" | "OVERRIDE_HOURS" | "OVERRIDE_DAY_OFF" | "NON_WORKING_DAY" | "INACTIVE";
        /** DashboardRead */
        DashboardRead: {
            /**
             * Date
             * Format: date
             * @description Clinic-local date the statistics refer to.
             */
            date: string;
            /**
             * Patients Seen Today
             * @description Distinct patients with a COMPLETED appointment on this date.
             */
            patients_seen_today: number;
            /**
             * Therapists On Duty Today
             * @description Active therapists whose resolved schedule (overrides included) has them working on this date.
             */
            therapists_on_duty_today: number;
            /**
             * Revenue Collected Today
             * @description Sum of PAID invoice totals whose paid_at falls on this clinic date.
             */
            revenue_collected_today: string;
            /**
             * Open Slots Remaining Today
             * @description Generated slots of on-duty therapists minus non-cancelled appointments.
             */
            open_slots_remaining_today: number;
            /** Total Slots Today */
            total_slots_today: number;
            /** Booked Slots Today */
            booked_slots_today: number;
            /** Therapist Capacity */
            therapist_capacity: components["schemas"]["TherapistCapacity"][];
            /**
             * Recent Patients
             * @description The 5 most recently added.
             */
            recent_patients: components["schemas"]["RecentPatient"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @example APPOINTMENT_CONFLICT
             */
            code: string;
            /**
             * Message
             * @example Therapist already has an appointment during this time.
             */
            message: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /**
         * Gender
         * @enum {string}
         */
        Gender: "MALE" | "FEMALE" | "OTHER";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceCreate */
        InvoiceCreate: {
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            /**
             * Service
             * @example Physiotherapy session x5
             */
            service: string;
            /**
             * Subtotal
             * @example 1500.00
             */
            subtotal: number | string;
            /**
             * Discount
             * @default 0.00
             * @example 1500.00
             */
            discount: number | string;
            /**
             * Status
             * @default DUE
             * @enum {string}
             */
            status: "PAID" | "DUE";
            /** @description Required when status is PAID. */
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            /**
             * Paid At
             * @description Defaults to now when status is PAID; must be omitted if DUE.
             */
            paid_at?: string | null;
        };
        /** InvoiceRead */
        InvoiceRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Invoice Number
             * @example INV-2026-000001
             */
            invoice_number: string;
            /**
             * Patient Id
             * Format: uuid
             */
            patient_id: string;
            patient: components["schemas"]["PatientSummary"];
            /** Service */
            service: string;
            /** Subtotal */
            subtotal: string;
            /** Discount */
            discount: string;
            /**
             * Total
             * @description subtotal - discount, computed by the database.
             */
            total: string;
            status: components["schemas"]["InvoiceStatus"];
            payment_method: components["schemas"]["PaymentMethod"] | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Paid At */
            paid_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InvoiceStatus
         * @enum {string}
         */
        InvoiceStatus: "PAID" | "DUE" | "VOID";
        /**
         * InvoiceUpdate
         * @description Partial update, e.g. `{"status": "PAID", "payment_method": "CASH"}` to mark as paid.
         *     Amount rules are re-checked after merging with the stored invoice.
         */
        InvoiceUpdate: {
            /** Service */
            service?: string | null;
            /** Subtotal */
            subtotal?: (number | string) | null;
            /** Discount */
            discount?: (number | string) | null;
            /** Status */
            status?: ("PAID" | "DUE") | null;
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            /** Paid At */
            paid_at?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Identifier
             * @description Email address or username (case-insensitive).
             * @example admin@physiodesk.local
             */
            identifier: string;
            /**
             * Password
             * @example Admin123!
             */
            password: string;
        };
        /** NextAppointment */
        NextAppointment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Appointment Date
             * Format: date
             */
            appointment_date: string;
            /**
             * Start Time
             * @example 09:00
             */
            start_time: string;
            /** Therapist Name */
            therapist_name: string;
        };
        /** Page[AppointmentRead] */
        Page_AppointmentRead_: {
            /** Items */
            items: components["schemas"]["AppointmentRead"][];
            /**
             * Page
             * @example 1
             */
            page: number;
            /**
             * Page Size
             * @example 20
             */
            page_size: number;
            /**
             * Total
             * @example 100
             */
            total: number;
            /**
             * Pages
             * @example 5
             */
            pages: number;
        };
        /** Page[InvoiceRead] */
        Page_InvoiceRead_: {
            /** Items */
            items: components["schemas"]["InvoiceRead"][];
            /**
             * Page
             * @example 1
             */
            page: number;
            /**
             * Page Size
             * @example 20
             */
            page_size: number;
            /**
             * Total
             * @example 100
             */
            total: number;
            /**
             * Pages
             * @example 5
             */
            pages: number;
        };
        /** Page[PatientRead] */
        Page_PatientRead_: {
            /** Items */
            items: components["schemas"]["PatientRead"][];
            /**
             * Page
             * @example 1
             */
            page: number;
            /**
             * Page Size
             * @example 20
             */
            page_size: number;
            /**
             * Total
             * @example 100
             */
            total: number;
            /**
             * Pages
             * @example 5
             */
            pages: number;
        };
        /** PatientCreate */
        PatientCreate: {
            /**
             * Full Name
             * @example Sita Sharma
             */
            full_name: string;
            /**
             * Phone
             * @example +977 9841234567
             */
            phone: string;
            /**
             * Age
             * @example 42
             */
            age: number;
            gender: components["schemas"]["Gender"];
            /** Address */
            address?: string | null;
            /**
             * Condition
             * @example Lower back pain
             */
            condition: string;
            /** Assigned Therapist Id */
            assigned_therapist_id?: string | null;
            /**
             * Package
             * @example 10-session rehab package
             */
            package?: string | null;
            /** @default ACTIVE */
            status: components["schemas"]["PatientStatus"];
        };
        /**
         * PatientDetail
         * @description Profile overview. Full session and billing history are served by the
         *     `/patients/{id}/appointments` and `/patients/{id}/invoices` sub-resources.
         */
        PatientDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Age */
            age: number;
            gender: components["schemas"]["Gender"];
            /** Address */
            address: string | null;
            /** Condition */
            condition: string;
            /** Assigned Therapist Id */
            assigned_therapist_id: string | null;
            assigned_therapist: components["schemas"]["TherapistSummary"] | null;
            /** Package */
            package: string | null;
            status: components["schemas"]["PatientStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            stats: components["schemas"]["PatientStats"];
        };
        /** PatientRead */
        PatientRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Age */
            age: number;
            gender: components["schemas"]["Gender"];
            /** Address */
            address: string | null;
            /** Condition */
            condition: string;
            /** Assigned Therapist Id */
            assigned_therapist_id: string | null;
            assigned_therapist: components["schemas"]["TherapistSummary"] | null;
            /** Package */
            package: string | null;
            status: components["schemas"]["PatientStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PatientStats */
        PatientStats: {
            /** Completed Sessions */
            completed_sessions: number;
            /** Upcoming Appointments */
            upcoming_appointments: number;
            /** Cancelled Appointments */
            cancelled_appointments: number;
            /**
             * Last Visit Date
             * @description Date of the latest COMPLETED session.
             */
            last_visit_date: string | null;
            next_appointment: components["schemas"]["NextAppointment"] | null;
            /**
             * Total Paid
             * @description Sum of PAID invoice totals.
             */
            total_paid: string;
            /**
             * Outstanding Balance
             * @description Sum of DUE invoice totals.
             */
            outstanding_balance: string;
        };
        /**
         * PatientStatus
         * @enum {string}
         */
        PatientStatus: "ACTIVE" | "COMPLETED" | "ON_HOLD";
        /** PatientSummary */
        PatientSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
        };
        /** PatientUpdate */
        PatientUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Age */
            age?: number | null;
            gender?: components["schemas"]["Gender"] | null;
            /** Address */
            address?: string | null;
            /** Condition */
            condition?: string | null;
            /** Assigned Therapist Id */
            assigned_therapist_id?: string | null;
            /** Package */
            package?: string | null;
            status?: components["schemas"]["PatientStatus"] | null;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "CASH" | "CARD" | "BANK_TRANSFER" | "OTHER";
        /** RecentPatient */
        RecentPatient: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Full Name */
            full_name: string;
            /** Condition */
            condition: string;
            assigned_therapist: components["schemas"]["TherapistSummary"] | null;
            /** Package */
            package: string | null;
            status: components["schemas"]["PatientStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ScheduleOverrideCreate */
        ScheduleOverrideCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Is Day Off
             * @description True: therapist is off. False: works custom hours.
             * @default false
             */
            is_day_off: boolean;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ScheduleOverrideRead */
        ScheduleOverrideRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Therapist Id
             * Format: uuid
             */
            therapist_id: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Is Day Off */
            is_day_off: boolean;
            /** Start Time */
            start_time: string | null;
            /** End Time */
            end_time: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScheduleOverrideUpdate */
        ScheduleOverrideUpdate: {
            /** Date */
            date?: string | null;
            /** Is Day Off */
            is_day_off?: boolean | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ScheduleRead */
        ScheduleRead: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Therapists */
            therapists: components["schemas"]["TherapistScheduleRead"][];
        };
        /** ScheduleSlotRead */
        ScheduleSlotRead: {
            /**
             * Start Time
             * @example 09:00
             */
            start_time: string;
            /**
             * End Time
             * @example 09:00
             */
            end_time: string;
            status: components["schemas"]["SlotStatus"];
            /** Appointment Id */
            appointment_id?: string | null;
            appointment_status?: components["schemas"]["AppointmentStatus"] | null;
            /** Patient Id */
            patient_id?: string | null;
            /** Patient Name */
            patient_name?: string | null;
        };
        /**
         * SessionType
         * @enum {string}
         */
        SessionType: "ASSESSMENT" | "TREATMENT" | "FOLLOW_UP";
        /**
         * SlotStatus
         * @enum {string}
         */
        SlotStatus: "OPEN" | "BOOKED" | "THERAPIST_OFF";
        /** TherapistCapacity */
        TherapistCapacity: {
            therapist: components["schemas"]["TherapistSummary"];
            /**
             * Working Start
             * @example 09:00
             */
            working_start: string;
            /**
             * Working End
             * @example 09:00
             */
            working_end: string;
            /** Total Slots */
            total_slots: number;
            /**
             * Booked Slots
             * @description Slots holding a BOOKED or COMPLETED appointment.
             */
            booked_slots: number;
            /** Open Slots */
            open_slots: number;
        };
        /** TherapistCreate */
        TherapistCreate: {
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /**
             * Working Days
             * @description ISO weekdays: 1 = Monday ... 7 = Sunday. Duplicates are removed.
             * @example [
             *       1,
             *       2,
             *       3,
             *       4,
             *       5
             *     ]
             */
            working_days: number[];
            /**
             * Start Time
             * Format: time
             * @example 09:00
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             * @example 09:00
             */
            end_time: string;
            /**
             * Slot Duration Minutes
             * @example 30
             */
            slot_duration_minutes: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** TherapistListItem */
        TherapistListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /** Working Days */
            working_days: number[];
            /**
             * Start Time
             * @example 09:00
             */
            start_time: string;
            /**
             * End Time
             * @example 09:00
             */
            end_time: string;
            /** Slot Duration Minutes */
            slot_duration_minutes: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Patients Seen Today
             * @description Distinct patients with a COMPLETED appointment with this therapist today.
             */
            patients_seen_today: number;
            /**
             * Weekly Hours
             * @description Regular scheduled hours per week.
             */
            readonly weekly_hours: number;
        };
        /** TherapistRead */
        TherapistRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
            /** Working Days */
            working_days: number[];
            /**
             * Start Time
             * @example 09:00
             */
            start_time: string;
            /**
             * End Time
             * @example 09:00
             */
            end_time: string;
            /** Slot Duration Minutes */
            slot_duration_minutes: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Weekly Hours
             * @description Regular scheduled hours per week.
             */
            readonly weekly_hours: number;
        };
        /** TherapistScheduleRead */
        TherapistScheduleRead: {
            /**
             * Therapist Id
             * Format: uuid
             */
            therapist_id: string;
            /** Therapist Name */
            therapist_name: string;
            /** Specialty */
            specialty: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Is Working */
            is_working: boolean;
            availability_source: components["schemas"]["AvailabilitySource"];
            /** Working Start */
            working_start: string | null;
            /** Working End */
            working_end: string | null;
            /** Slot Duration Minutes */
            slot_duration_minutes: number;
            /** Slots */
            slots: components["schemas"]["ScheduleSlotRead"][];
        };
        /** TherapistSummary */
        TherapistSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Specialty */
            specialty: string;
        };
        /** TherapistUpdate */
        TherapistUpdate: {
            /** Name */
            name?: string | null;
            /** Specialty */
            specialty?: string | null;
            /** Working Days */
            working_days?: number[] | null;
            /** Start Time */
            start_time?: string | null;
            /** End Time */
            end_time?: string | null;
            /** Slot Duration Minutes */
            slot_duration_minutes?: number | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires In
             * @description Access token lifetime in seconds.
             */
            expires_in: number;
            /**
             * Refresh Expires In
             * @description Refresh token lifetime in seconds.
             */
            refresh_expires_in: number;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Username */
            username: string;
            role: components["schemas"]["UserRole"];
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "ADMIN" | "STAFF";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patients_api_v1_patients_get: {
        parameters: {
            query?: {
                /** @description Case-insensitive match on name or phone. */
                search?: string | null;
                /** @description Assigned therapist. */
                therapist_id?: string | null;
                status?: components["schemas"]["PatientStatus"] | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PatientRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_patient_api_v1_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_api_v1_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patient_api_v1_patients__patient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_patient_api_v1_patients__patient_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patient_appointments_api_v1_patients__patient_id__appointments_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AppointmentStatus"] | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AppointmentRead_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_patient_invoices_api_v1_patients__patient_id__invoices_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["InvoiceStatus"] | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                page_size?: number;
            };
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvoiceRead_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_therapists_api_v1_therapists_get: {
        parameters: {
            query?: {
                /** @description Filter by active flag. */
                is_active?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_therapist_api_v1_therapists_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TherapistCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistRead"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_therapist_api_v1_therapists__therapist_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_therapist_api_v1_therapists__therapist_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_therapist_api_v1_therapists__therapist_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TherapistUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TherapistRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_overrides_api_v1_therapists__therapist_id__schedule_overrides_get: {
        parameters: {
            query?: {
                /** @description Inclusive lower bound. */
                date_from?: string | null;
                /** @description Inclusive upper bound. */
                date_to?: string | null;
            };
            header?: never;
            path: {
                therapist_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOverrideRead"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_override_api_v1_therapists__therapist_id__schedule_overrides_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleOverrideCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOverrideRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_override_api_v1_therapists__therapist_id__schedule_overrides__override_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
                override_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_override_api_v1_therapists__therapist_id__schedule_overrides__override_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                therapist_id: string;
                override_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScheduleOverrideUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOverrideRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_appointments_api_v1_appointments_get: {
        parameters: {
            query?: {
                /** @description Exact date. */
                date?: string | null;
                /** @description Inclusive lower bound. */
                date_from?: string | null;
                /** @description Inclusive upper bound. */
                date_to?: string | null;
                therapist_id?: string | null;
                patient_id?: string | null;
                status?: components["schemas"]["AppointmentStatus"] | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AppointmentRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_appointment_api_v1_appointments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_appointment_api_v1_appointments__appointment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_appointment_api_v1_appointments__appointment_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_appointment_api_v1_appointments__appointment_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appointment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppointmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppointmentRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_schedule_api_v1_schedule_get: {
        parameters: {
            query?: {
                /** @description Clinic-local date; defaults to today. */
                date?: string | null;
                therapist_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_invoices_api_v1_invoices_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["InvoiceStatus"] | null;
                patient_id?: string | null;
                /** @description Match on invoice number or patient name. */
                search?: string | null;
                /** @description 1-based page number. */
                page?: number;
                /** @description Items per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InvoiceRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_invoice_api_v1_invoices_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_invoice_api_v1_invoices__invoice_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    void_invoice_api_v1_invoices__invoice_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_invoice_api_v1_invoices__invoice_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoice_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Database unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
